- name: Set Arch local workstation
  hosts: local
  roles:
    - role: user
    - role: sudo
    - role: xorg
    - role: lightdm
    - role: gtk
    - role: bspwm
    - role: sxhkd
    - role: alacritty
