---
  - name: Add user
    user:
      name: "{{ username }}"
      groups: wheel
      shell: /bin/bash
      append: yes
  
  - name: Sudo | add to sudoers file and validate
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^{{ username }} '
      line: '{{username}} ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
