---

  - name: Ensure sxhkd package is installed
    become: yes
    pacman:
      name: "{{ sxhkd_packages_name }}"
      state: latest
      update_cache: yes
  
  - name: Create sxhkd config file
    copy:
      dest: "/home/{{ username }}/.config"
      group: "{{ username }}"
      mode: 0655
      owner: "{{ username }}"
      src: sxhkd
  
  - name: Add xdg profile unit
    become: yes
    copy:
      dest: "/etc/profile.d/xdg.sh"
      group: root
      mode: 0644
      owner: root
      src: xdg.sh
  