---
  - name: Ensure gtk package is installed
    become: yes
    pacman:
      name: "{{ gtk_packages }}"
      state: latest
      update_cache: yes
  
  - name: Create gtk config file
    copy:
      dest: "/home/{{ username }}/.config"
      group: "{{ username }}"
      mode: 0655
      owner: "{{ username }}"
      src: gtk-3.0