---
  - name: Create aur_builder user
    user:
      name: aur_builder
      group: wheel
      system: yes

  - name: Add user
    user:
      name: "{{ username }}"
      groups: wheel
      shell: /usr/bin/fish
      append: yes
  
  - name: Allow to change expired passwords on login
    become: yes
    pamd:
      control: include
      module_path: system-local-login
      name: login
      new_control: include
      new_module_path: system-local-login
      new_type: password
      type: session
      state: before
    
  - name: Unlock password and set it to empty
    become: yes
    command: passwd -d "{{ username }}"
    
  - name: Expire password
    become: yes
    command: chage -d 0 "{{ username }}"
    