---

- name: Ensure rofi package is installed
  become: yes
  pacman:
    name: "{{ rofi_package_name }}"
    state: latest
    update_cache: yes

- name: Copy rofi themes
  copy:
    dest: "/home/{{ username }}/.config"
    group: "{{ username }}"
    mode: 0655
    owner: "{{ username }}"
    src: rofi

- name: Create rofi config file
  template:
    dest: "/home/{{ username }}/.config/rofi/config.rasi"
    group: "{{ username }}"
    mode: 0644
    owner: "{{ username }}"
    src: "config.rasi.j2"
