---

  - name: Ensure required packages are installed
    become: yes
    package:
      name: "{{ lightdm_packages }}"
      state: latest
      update_cache: yes
  
  - name: Create config and theme directories
    become: yes
    file:
      mode: 0755
      path: "{{ item }}"
      state: directory
    loop:
      - '/etc/lightdm'
      - '/usr/share/lightdm-webkit/themes'
  
 # - name: Clone theme
 #   become: yes
 #   git:
 #     dest: '/usr/share/lightdm-webkit/themes/lightdm-webkit2-dmg_blue'
 #     repo: "https://github.com/davidmogar/lightdm-webkit2-dmg_blue.git"
  


  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    ansible.builtin.unarchive:
      src: https://github.com/manilarome/lightdm-webkit2-theme-glorious/releases/download/v2.0.5/lightdm-webkit2-theme-glorious-2.0.5.tar.gz
      dest: /usr/share/lightdm-webkit/themes
      remote_src: yes
 
  - name: Move foo to bar
    command: mv /usr/share/lightdm-webkit/themes/lightdm-webkit2-theme-glorious-2.0.5 /usr/share/lightdm-webkit/themes/glorious

  - name: Create lightdm config file
    become: yes
    copy:
      dest: '/etc/lightdm/lightdm.conf'
      mode: 0644
      src: 'lightdm.conf'
  
  - name: Create lightdm-webkit2-greeter config file
    become: yes
    template:
      dest: '/etc/lightdm/lightdm-webkit2-greeter.conf'
      mode: 0644
      src: 'lightdm-webkit2-greeter.conf.j2'

  - name: Add script to set screen resolution
    become: yes
    copy:
      dest: "/usr/share/lightdm_setup_screen_resolution.sh"
      group: root
      mode: 0744
      owner: root
      src: lightdm_setup_screen_resolution.sh