---

- name: Ensure neofetch is installed
  become: yes
  pacman:
    name: "{{ neofetch_package_name }}"
    state: latest
    update_cache: yes

- name: Copy config files
  copy:
    dest: "/home/{{ username }}/.config"
    group: "{{ username }}"
    mode: 0755
    owner: "{{ username }}"
    src: neofetch
