---

  - name: Ensure required packages are installed
    become: yes
    pacman:
      name: "{{ alacritty_package_name }}"
      state: latest
      update_cache: yes
  
  - name: Create config directory
    file:
      group: "{{ username }}"
      mode: 0755
      owner: "{{ username }}"
      path: "/home/{{ username }}/.config/alacritty"
      state: directory
  
  - name: Create alacritty config file
    template:
      dest: "/home/{{ username }}/.config/alacritty/alacritty.yml"
      group: "{{ username }}"
      mode: 0644
      owner: "{{ username }}"
      src: "alacritty.yml.j2"
  